name: deploy-api-docs
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
     uses: vapor/api-docs/.github/workflows/build-and-deploy-docs-workflow.yml@8d28281fe89fd836116d59c7fe217df651ebf41a
     secrets: inherit
     with:
       package_name: postgres-nio
       modules: PostgresNIO
